<a href="https://colab.research.google.com/github/mikeamerenda/mikeamerenda/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
price = [2,1,10]
type(price)

list

In [2]:
quantity_sold = [17,40,1]
type(quantity_sold)

list

In [3]:
import numpy as np

In [4]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [5]:
price_array * quantity_sold_array

array([34, 40, 10])

In [6]:
cost_array = np.array([0.25,0.50,5.00])

In [7]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [8]:
profit_array > 2.00

array([False, False,  True])

In [9]:
price_array = price_array +[7]
print(price_array)

[ 9  8 17]


In [10]:
# Just fixing the mistake
price_array = price_array - [7]
# he proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [11]:
price_array = np.append(price_array, [4.50,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [12]:
print(price_array.dtype)

float64


In [13]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [14]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [15]:
#2 Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [16]:
#2 You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantity_sold_array from 40 to 39.  
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [17]:
#3 Determine the amount of money collected from the sale of each item at the bake sale.  
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [18]:
#4 Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?
quantity_leftover_array = np.array([0,0,2,1,6,0,2])

In [19]:
#4
print(quantity_leftover_array)

[0 0 2 1 6 0 2]


In [22]:
#5 The club decides to sell the leftover items at half price and everything quickly sells out!  Determine how much money was collected from the clearance sale.  
quantity_leftover_array * (price_array/2)

array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [28]:
#6 How much total money was collected from the bake sale (including the sale of full price and clearance items)?
((price_array * quantity_sold_array + (quantity_leftover_array * (price_array/2))))

array([34. , 39. , 24. , 17.5, 27. , 48. , 24. ])

In [29]:
#6 in Sum format
np.sum((price_array * quantity_sold_array + (quantity_leftover_array * (price_array/2))))

213.5